In [2]:
import numpy as np
import pandas as pd

## Creating

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [6]:
arr = np.array(42)
print(arr)

42


In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [9]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
arr3 = np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[1, 2, 3]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]]


In [11]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [13]:
arr4 = np.array([1, 2, 3, 4], ndmin = 4)
print(arr4)
print("Number of dimensions :", arr4.ndim)

[[[[1 2 3 4]]]]
Number of dimensions : 4


## Indexing

In [23]:
print(arr1[2])

3


In [22]:
print(arr1[2]+arr1[3])

7


In [26]:
print("2nd element on 1st row: ", arr2[0,1])

2nd element on 1st row:  2


In [27]:
print("3rd element of second array of the first array: ", arr3[0,1,2])

3rd element of second array of the first array:  6


In [28]:
print("Last element from 2nd dimension: ", arr2[1,-1])

Last element from 2nd dimension:  6


## Slicing

In [30]:
# Slice elements from index 1 to index 5 from the following array
print(arr1[1:5])

[2 3 4 5]


In [32]:
# Slice elements from index 1 to index 5 from the following array
print(arr1[4:])

[5]


In [36]:
# Slice from the index 3 from the end to index 1 from the end
print(arr1[-3: -1])

[3 4]


In [38]:
# Return every other element from index 1 to index 5
print(arr1[1: 5: 2])

[2 4]


In [42]:
# Return every other element from the entire array
print(arr1[::2])

[1 3 5]


In [47]:
# From the second element, slice elements from index 1 to index 4 (not included)
print(arr2[1, 1:4])

[5 6]


In [43]:
# From both elements, return index 2
print(arr2[0: 2, 2])

[3 6]


In [49]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
print(arr2[0: 2, 1: 4])

[[2 3]
 [5 6]]


## Data Types

In [50]:
arr = np.array([1.32, 4.32, 4.13], dtype = np.float64)
print(arr)

[1.32 4.32 4.13]


## Data Cleaning

In [51]:
array_with_nan = np.array([1.0, np.nan, 3.0, np.nan, 5.0])
nan_mask = np.isnan(array_with_nan)
print("Original array:", array_with_nan)
print("NaN mask:", nan_mask)

Original array: [ 1. nan  3. nan  5.]
NaN mask: [False  True False  True False]
